// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk6fm-BtZi1WaUcQmvdNex0cDMOZgeDtc',
    appId: '1:1049602785511:web:f5c44749fc2929982ca242',
    messagingSenderId: '1049602785511',
    projectId: 'food-delivery-5e75d',
    authDomain: 'food-delivery-5e75d.firebaseapp.com',
    storageBucket: 'food-delivery-5e75d.appspot.com',
    measurementId: 'G-K7TBXL5HJK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2_xkFRfmghiMhtUrg4UvREGjohZGb9yY',
    appId: '1:1049602785511:android:7d549fd2e03fb73a2ca242',
    messagingSenderId: '1049602785511',
    projectId: 'food-delivery-5e75d',
    storageBucket: 'food-delivery-5e75d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbmJFrYKN6Ohccv2M8yrJx6NlzxT-kAHs',
    appId: '1:1049602785511:ios:33c11558d4d30f382ca242',
    messagingSenderId: '1049602785511',
    projectId: 'food-delivery-5e75d',
    storageBucket: 'food-delivery-5e75d.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbmJFrYKN6Ohccv2M8yrJx6NlzxT-kAHs',
    appId: '1:1049602785511:ios:b7d810e837a5fe582ca242',
    messagingSenderId: '1049602785511',
    projectId: 'food-delivery-5e75d',
    storageBucket: 'food-delivery-5e75d.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp.RunnerTests',
  );
}
